const fs = require('fs');
const path = require('path');
const file = path.join(__dirname, 'src/pages/TeacherProfile.jsx');
const s = fs.readFileSync(file, 'utf8');
const count = (ch) => [...s].filter((c) => c === ch).length;
console.log('backtick', count('`'));
console.log('singleQuote', count("'"));
console.log('doubleQuote', count('"'));
console.log('slash', count('/'));
console.log('lineCount', s.split(/\r?\n/).length);
